[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-explorer-api"
version = "0.1"
description = "Component that containts API for graph explorer."
dependencies = []

[tool.setuptools]
provides = ["sok.graph.explorer.api.services"]